### ISSUE TITLE
Request for musdb_torch Module

### ISSUE THREAD

**Issue by happyTonakai** [Thodoris1999/UNet-pytorch#1]
Dear Thodoris,

I'm a beginner in music source separation and recently came across your work and am very interested in it. However, I noticed that the `musdb_torch` module in `train.py`, which appears to convert audio waves from the musdb18 dataset to spectrograms, is missing. My attempts to find it online were unsuccessful. Could you kindly provide the link or the source code for this module?

Thank you.

Best regards,
Han

**Comment by Thodoris1999** [comment]
Well... that's awkward, I can't find anything on it either so I guess I just forgot to upload that file. I don't have a local copy anymore either, but I think I can recreate it over the weekend, since it seems to just be a `torch.utils.data.Dataset` that loads musdb data into spectrograms (presumably using torchaudio's [spectrogram)](https://pytorch.org/audio/master/generated/torchaudio.functional.spectrogram.html#torchaudio.functional.spectrogram).

**Comment by happyTonakai** [comment]
Thank you very much! Looking forward to it!

**Comment by Thodoris1999** [comment]
Here you go https://github.com/Thodoris1999/UNet-pytorch/commit/6bf3387c4babbad9ab86aa6bc858db643cfb0bbc, let me know if that works for you

**Comment by happyTonakai** [comment]
Thank you. I'll try it out asap.

**Comment by happyTonakai** [comment]
Sorry for the late response. It works fine now. Thank you again.
